<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-03-04 15:46

$extensionPath = t3lib_extMgm::extPath('felogindebug');
return array(
	'tx_felogindebug_pi1' => $extensionPath . 'pi1/class.tx_felogindebug_pi1.php',
);
?>